

//Auth types

export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_START='USER_LOGIN_START'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'
export const USER_LOGOUT='USER_LOGOUT'
export const USER_LOGIN_LOGOUT_PAGE='USER_LOGIN_LOGOUT_PAGE'
export const NOT_USER_LOGIN_LOGOUT_PAGE='NOT_USER_LOGIN_LOGOUT_PAGE'
export const USER_SEARCH='USER_SEARCH'
export const USER_REGISTER_START='USER_REGISTER_START'
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED' 
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS' 
export const USER_CHANGE_PASSWORD_FAILED='USER_CHANGE_PASSWORD_FAILED'
export const USER_CHANGE_PASSWORD_START='USER_CHANGE_PASSWORD_START'
export const USER_CHANGE_PASSWORD_SUCCESS='USER_CHANGE_PASSWORD_SUCCESS'
export const COUNT_CART='COUNT_CART'

//Auth